
results_dir : "./exp/"
vis_test_dir : "/nas/home/gmuffiness/result/"
data_dir:
  synthtext : "/data/SynthText/"
  synthtext_gt : null
  ic15 : "/data/ICDAR2015/"
  ic13 : "/data/ICDAR2013/"

train:
  ckpt_path: null
  batch_size: 8
  st_iter: 0
  end_iter: 10
  lr: 0.1e-4
  lr_decay: 10000
  gamma: 0.8
  weight_decay: 0.1e-4
  num_workers: 0
  amp: True
  loss: 3
  neg_rto: 3
  data:
    output_size: 768
    enlarge_size : 0.75
    gauss_init_size: 200
    gauss_sigma: 40
    rnd_crop: "rnd_back"
    aug: True
    logging: False

test:
  test_folder: "/data/ICDAR2013/"
  trained_model: ""
  text_threshold: 0.85 # ICDAR2015 0.85
  low_text: 0.5 # ICDAR2015 0.5
  link_threshold: 0.2 # ICDAR2013: 0.2
  cuda: True
  canvas_size: 960
  mag_ratio: 1.5
  poly: False
  isTraingDataset: False


