
results_dir : "./exp/"

data_dir:
  synthtext : "/home/data/ocr/detection/SynthText/SynthText/"
  synthtext_gt : "/home/data/ocr/detection/SynthText/SynthText/"
  ic15 : "/home/data/ocr/detection/ICDAR2015/"
  ic13 : "/home/data/ocr/detection/ICDAR2013/"

train:
  ckpt_path: null
  batch_size: 16
  st_iter: 0
  end_iter: 1000
  lr: 0.1e-4
  lr_decay: 10000
  gamma: 0.8
  weight_decay: 0.1e-4
  num_workers: 0
  amp: True
  loss: 3
  neg_rto: 3
  data:
    output_size: 768
    enlargeSize: 0.75
    rnd_crop: "rnd_back"
    aug: True
    logging: False

test:
  test_folder: "/home/data/ocr/detection/ICDAR2013/"
  trained_model: "./exp/backnew-base-best-syn-CRAFT_clr_95000.pth"
  text_threshold: 0.85 # ICDAR2015 0.85
  low_text: 0.5 # ICDAR2015 0.5
  link_threshold: 0.2 # ICDAR2013: 0.2
  cuda: True
  canvas_size: 960
  mag_ratio: 1.5
  poly: False
  isTraingDataset: False


